### ISSUE TITLE
Creating map layer at 10 fig grid reference

### ISSUE THREAD

**Issue by DrGwenH** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#24]
I'm working on orchid records with a nature reserve with the raw data in a cvs file with each row being a single record and a 10fig grid reference. I've managed to crate some very useful maps showing the records as points & on a 10m atlas squares styled to show difference abundance levels. 
What would also be useful is a way to create a 1m atlas squares which would effectively combine all the data points which have the same 10-fig grid references and allow abundance levels to be shown in a much finer scale. Is it possible to get this added as an option? (I realise it's only applicable to within site projects like mine) Or is there another way to do this? Quite a few of our spreadsheets from survey work end up with several records at the same grid reference, I could manipulate the data in excel to combine rows but if there's an easy way to do it in QGIS that would be great.
Thanks!
(Sorry if this isn't the best platform to raise this - I was directed here by the chap running our training course!)

**Comment by burkmarr** [comment]
Hi - thanks for your question. It's fine to put questions like that here so that other people can potentially read and learn from them tool. 

As you've found, there's no 1m aggregation options - I'm not sure why I left that out and I will add it for the next release. In the meantime, you could try this workflow. 

1. Map your records using the 'records as grid squares' option.
2. Use the 'delete duplicate geometries' tool from processing toolbox to create new temporary layer with a single square at each 10 fig GR.
3. Use the 'join attributes by location (summary)' tool to create a new layer based on the temp layer you just created that counts all the squares from the original layer that are 'contained' within the square from the temp layer. When running this tool, you will need to select an attribute from the original layer and specify that it is to be 'counted'. Alternatively, if you have an abundance attribute in your original layer, you can chose to 'sum' those values.

That will all give you a new layer with a single geometry for each unique square and an attribute which counts (or sums an attribute value) all those squares from the original layer at each square position. Hope that's a useful workaround for now.

**Comment by DrGwenH** [comment]
Thank Rich, that work around sounds like it’ll give exactly what I was interested in.

Cheers!

Gwen

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add 1 metre aggregation option](https://trello.com/c/bYzTI1oN/26-add-1-metre-aggregation-option)

**Comment by burkmarr** [comment]
Already actioned.
