### ISSUE TITLE
POLYGON SELECTION NOT ALWAYS WORKING FOR NBN TOOL

### ISSUE THREAD

**Issue by bwmoths** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#29]
I think I have a similar problem to issue #22 closed recently. On my system I have found that the polygon selection does not work for polygon shapefile layers (PSL) created in previous uses of a QGIS Project.
If I create a PSL in a project and select it with NBN TOOL open then the 'polygon' box gets a tick and the filter works OK. If then the NBNTOOL is closed the project saved and then shut down, when reopening the project and using the NBN TOOL the previousely created PSL can be selected as before but the 'polygon' box does not get a tick and the filter fails ?  Never to work again unless the PSL is deleted and recreated when it will work until the project closed as before. Am I doing something wrong ? I think I had had this before the QGIS 3.4.3 upgrade ?
Martin

**Comment by burkmarr** [comment]
Thanks for another detailed description Martin which has enabled me to reproduce the problem and therefore (I hope) should enable me to fix it. I am working on a new major release of the software so this will be addressed within that. Should be ready for release in 2 to 4 weeks, all being well.

**Comment by burkmarr** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Polygon filter for NBN queries not always working as expected.](https://trello.com/c/XmcIPS4h/37-polygon-filter-for-nbn-queries-not-always-working-as-expected)

**Comment by bwmoths** [comment]
Thanks Rich, good luck with your 'major release' !
Regards martin

**Comment by burkmarr** [comment]
Thanks Martin. (Strictly speaking I guess that it is a 'minor' release - it will be 3.2.n.)

**Comment by burkmarr** [comment]
This turned out to be because code was using feature.geometry().wkbType() to detect geometry instead of feature.geometry().type(). The former detects different types of geometries within specific topological types so, for example, polygons and multi-polygons are differentiated. Code was only looking for polygons so mutli-polygons were missed. Instead now use type which only distiguishes major topological types, so all types of polygon treated together. Fixed for upcoming release 3.2.

**Comment by bwmoths** [comment]
Hmm interesting, thank's for the info. I look forward as  before to the new release. Cheers.
