### ISSUE TITLE
Generate Atlas Images button missing

### ISSUE THREAD

**Issue by zul-b** [FieldStudiesCouncil/QGIS-Biological-Recording-Tools#54]
I am an inexperienced user, so probably doing something daft but in the Options tab, I don't have a Generate atlas images button below the map mode drop down

**Comment by burkmarr** [comment]
It is right at the bottom of the dialog. Possibly those buttons are hidden for some reason in your docked dialog. Try undocking it - i.e. drag it away from it's docked position so that it is free standing - to see if you can see it. It's a toolbutton with a floppy disk icon.

**Comment by zul-b** [comment]
Thank you.  I see it now where you say it is although when I click it, it says "Output folder does not exist" and doesn't give me an option to choose one.  On the tutorial I was following the option for making and image or multiple ones was immediately below the single map / batch map mode button with a browse button next to it

**Comment by burkmarr** [comment]
It sounds like that might be describing an earlier version. This is what you need: https://www.fscbiodiversity.uk/qgisplugin/biorecstool. It's quite a long read because the tool is complex, but the bit you need is under the heading **Output options** about 2/3 of the way down. Scroll down until you find that.
